config/routes.rb
Rails.application.routes.draw do

  root 'home#home'

  get '/about', to: 'home#about'

  resources :posts do
    resources :comments
end

  resources :tags

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  get '/sign_up', to: 'users#new', as: :sign_up
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, length:{ minimum: 2}
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, :dependent => :delete_all
    has_many :taggings, :dependent => :delete_all
    has_many :tags, through: :taggings

    belongs_to :user

    has_many_attached :uploads
    
    has_rich_text :body

    
    def tag_list
        tags.join(', ')
    end

    def tag_list=(tag_string)
        tag_names = tag_string.split(',').collect{|s| s.strip.downcase}.uniq

        new_or_found_tags = tag_names.collect{|name| Tag.find_or_create_by(name: name)}

        self.tags = new_or_found_tags
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, :dependent => :delete_all
    has_many :posts, through: :taggings

    def to_s #Overriding default to_s method to return tag :name instead of tag reference
        name
    end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: {minimum: 8}
  validates :password, confirmation: true
  validates :email, uniqueness: true, email_format: {message: 'has invalid format'}
  validates :username, uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login


    private

    def not_authenticated
        flash[:warning] = "You must be authenticated to access this page!"
        redirect_to log_in_path
    end


    def check_admin
        unless current_user[:admin_user]
            redirect_to root_path
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.new(comment_params)
        @comment.post_id = params[:post_id]
        @comment.author_name = current_user.username

        if @comment.save
            flash.notice = 'New comment added'
            redirect_to post_path(@comment.post)
        else
            flash.notice = 'Error adding nw comment'
            redirect_to post_path(@comment.post)
        end
    end

    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :require_login
    def home
    end

    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    skip_before_action :require_login, only: [:index, :show]
    before_action :check_admin, only: [:edit, :new]
    
    def index
        @posts = Post.all
    end

    def show
        find_post

        @comment = Comment.new
        @comment.post_id = @post.id
    end

    def new
        @post = Post.new
    end

    def create
        @post  = Post.new(post_params)
        @post.user_id = current_user[:id]
        if  @post.save
            flash.notice = "Post '#{@post.title}' Created!"
            redirect_to post_path(@post)
        else
            flash.notice = "Post '#{@post.title}' Failed to Create!"
            render new
        end
    end

    def destroy
        find_post
        @post.destroy
        flash.notice = "Post '#{@post.title}' Destroyed!"
        redirect_to posts_path
    end

    def edit
        find_post
    end

    def update
        find_post
        if @post.update(post_params)
            flash.notice = "Post '#{@post.title}' Updated!"
            redirect_to post_path(@post)
        else
            flash.notice = "Post '#{@post.title}' Failed to Update!"
            render new
        end
    end

    private

    def find_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :body, :tag_list, uploads:[])
    end


end

app/controllers/sessions_controller.rb
class SessionsController <  ApplicationController
    skip_before_action :require_login, except: [:destroy]

    def new

    end

    def create
        if login(params[:email], params[:password],params[:remember_me])
            flash[:success] = 'Welcome back!'
            redirect_to root_path
        else
            flash.now[:warning] = 'Email and/or password is incorrect.'
            render 'new'
        end
    end

    def destroy
        logout
        flash[:success] = 'Goodbye!'
        redirect_to log_in_path
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    skip_before_action :require_login, only: [:show, :index]
    before_action :check_admin, except: [:show, :index]

    def index
        @tags = Tag.all
    end

    def show
        find_tag
    end

    def edit
        find_tag
    end

    def update
        find_tag
        @tag.update(tag_params)
    end


    def destroy
        find_tag
        @tag.destroy
        redirect_to tags_path
    end

    private

    def find_tag
        @tag = Tag.find(params[:id])
    end

    def tag_params
        params.require(:tag).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :require_login, only: [:new, :create]

    def new
        @user = User.new
    end


    def create
        @user = User.new(user_params)

        if @user.save
            login(params[:user][:email],params[:user][:password],params[:user][:remember_me])
            flash[:success] = "Welcome, #{@user.username}!"
            # fail
            redirect_to root_path
        else
            
            flash[:warning] = 'faileds'
            
            render new
        end
    end

    private

    def user_params
        # fail
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_form.html.erb
<div class="new-comment-container">
    <h3>Post a Comment</h3>
    <%= form_with model:[@post,@comment] do |f|%>
        
        <p>
            <%= f.label 'Your Comment:' %> <br/>
            <%= f.text_area :body, class: 'comment-input'%>
        </p>
        <p class='comment-submit-container'>
            <%= f.submit 'Post' %>
        </p>
    <% end %>
</div>

app/views/home/about.html.erb
<h2 class= "page-header">About Us</h2>
<div class="container-fluid">
    <section class = 'card'>
        <h3 class= 'card-title'>The site</h3>
        <p>Blurb about the site. Lorem ipsum dolor sit amet consectetur adipisicing elit. Non optio nostrum quia ullam. Aperiam sapiente illum ipsa consectetur magnam commodi corrupti ipsum consequuntur dolorum dolor et quisquam harum, vero laborum.</p>
    </section>
    <section class = 'card'>
        <div class="about-section-header">
            <div class="avatar" style="background-image: url('https://storage.googleapis.com/posts-media-assest/alex2-avatar.png')"></div>
            <h3 class= 'card-title'>Alex</h3>
        </div>
        <p>Blurb about me. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae odit incidunt aliquid, voluptate exercitationem a ea recusandae perferendis in dicta, expedita minima perspiciatis corrupti natus veniam minus, obcaecati ad illo.</p>
    </section>
    <section class = 'card'>
        <div class="about-section-header">
            <div class="avatar" style="background-image: url('https://storage.googleapis.com/posts-media-assest/other-member-avatar.jpg')"></div>
            <h3 class= 'card-title'>Imaginary Friend</h3>
        </div>
        <p>This is where I would put another team member's blurb... if I had one! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero sapiente, at, atque eos distinctio voluptatibus aperiam dolorem harum perspiciatis et tempore iusto voluptatem omnis architecto recusandae ad dolores soluta? Deleniti?</p>
    </section>
</div>

app/views/home/home.html.erb
<div class="home-container">
    <section class = 'card '>
        <div class="card-body">
            <h3 class='card-title'>What is it about?</h3>
           <p class = 'card-text'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et cupiditate molestias eum nobis, voluptas praesentium labore est molestiae quaerat delectus dignissimos illum quasi aut ratione magni iure, aliquam nemo saepe?</p>
        </div>
    </section>
    <section class = 'card'>
        <div class="card-body">
            <h3 class='card-title'>What can I do in it?</h3>
           <p class = 'card-text'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et cupiditate molestias eum nobis, voluptas praesentium labore est molestiae quaerat delectus dignissimos illum quasi aut ratione magni iure, aliquam nemo saepe?</p>
        </div>
    </section>
    <section class = 'card'>
        <div class="card-body">
            <h3 class='card-title'>When can I play it?</h3>
           <p class = 'card-text'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et cupiditate molestias eum nobis, voluptas praesentium labore est molestiae quaerat delectus dignissimos illum quasi aut ratione magni iure, aliquam nemo saepe?</p>
        </div>
    </section>
    <section class = 'card'>
        <div class="card-body">
            <h3 class='card-title'>What else can I know?</h3>
           <p class = 'card-text'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et cupiditate molestias eum nobis, voluptas praesentium labore est molestiae quaerat delectus dignissimos illum quasi aut ratione magni iure, aliquam nemo saepe?</p>
        </div>
    </section>
        <section class = 'card '>
        <div class="card-body">
            <h3 class='card-title'>Whats the plan?</h3>
           <p class = 'card-text'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et cupiditate molestias eum nobis, voluptas praesentium labore est molestiae quaerat delectus dignissimos illum quasi aut ratione magni iure, aliquam nemo saepe?</p>
        </div>
    </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameBlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700|Josefin+Slab&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class = "banner-container">
      <h1>Unnamed Game</h1>
    </div>
    <nav>
      <ul>
        <li><a href="<%=root_path%>">Home</a></li>
        <li><a href="/posts">Updates</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/tags">Tags</a></li>
        <% if current_user%>
          <li><%= link_to 'Log Out', log_out_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log In', log_in_path %></li>
          <% end %>
      </ul>
    </nav>
    
    
    <div class= 'inserted-content'>
    <p class="flash"><%=flash.notice%></p>
      <%= yield %>
    </div>


    <footer>
    </footer>

  </body>

</html>

app/views/posts/_comment.html.erb
<div class = "comment">
    <h4 class = 'comment-author'>Comment by <%= comment.author_name %></h4>
    <p class= 'comment-body'><%= comment.body %></p>
    <h5 class = "comment-posted"><%=comment.created_at.strftime("Posted on %d/%m/%Y %I:%M%p")%></h5>
</div>

app/views/posts/_form.html.erb
<%= form_with model: @post, class: 'post-form' do |f| %>
<ul>
    <% @post.errors.full_messages.each do |error|%>
        <li><%= error %></li>
    <% end %>
</ul>
    <p class = "post-form-title">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>
    <p class = 'post-form-body'>
        <%= f.label :body %>
        <%= f.rich_text_area :body%>
    </p>
    <p class = 'post-form-tags'>
        <%= f.label :tags_list%> <br/>
        <%= f.text_field :tag_list%>
    </p>
    <p class="post-form-files">
        <%= f.label 'Files' %>
        <%= f.file_field :uploads, multiple: true%>
    </p>
    <p class='submit-container'>
        <%= f.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<h2 class = "page-header">Edit post</h2>
<%= render partial: 'form'%>
<div class="btn-container">
    <%= link_to 'Back', post_path(@post), class: 'back-btn'%>
    <%= button_to "Delete", @post, method: :delete,data: { confirm: "Are you sure?" }, class: 'delete-btn' %>
</div>

app/views/posts/index.html.erb
<h2 class= "page-header">All Updates:</h2>
<% if current_user != nil && current_user[:admin_user] %>
    <div class = 'edit-btn-container'>
        <%= link_to 'NEW POST', new_post_path, class:'edit-btn'%> 
    </div>
<%end%>
<div class = 'post-list-container'>
    <% @posts.each do |post|%>
    <div class="post-item">
        <%= link_to post.title, post_path(post), class: 'post-link'%>
    </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h2 class = "page-header">New Post</h2>
<%= render partial: 'form' %>

app/views/posts/show.html.erb
<script src="https://cdn.babylonjs.com/viewer/babylon.viewer.js"></script>
<script>
    // setTimeout(() => window.location.reload(), 3000);
</script>
<div class = 'post-header'>
    <h2 class = "post-title"><%= @post.title %></h2>
    <h4>Tags: 
        <% @post.tags.each do |tag|%>
            <%= link_to tag.name, tag_path(tag)%>
        <% end %>
    </h4>
    <h4 class='post-creation'><span class = 'post-author'><%=@post.user.username%></span> <span><%=@post.created_at.strftime("Posted on %d/%m/%Y %I:%M%p")%></span></h3>
</div>

<%if current_user != nil && current_user[:admin_user] != false %>
    <div class ="edit-btn-container">
        <%= link_to 'EDIT', edit_post_path(@post), class: 'edit-btn'%>
    </div>
<% end %>

<% if @post.uploads.size !=0 %>
    <div class="carousel-to-be">
        <img src="<%= @post.uploads.first%>" alt="">
        <% @post.uploads.each do |upload|%>
            <%if upload.image? %>
                <img src="<%= url_for(upload)%>" alt="" srcset="" height='300'> 
            <% elsif upload.video? %>
                <video src="<%=url_for(upload)%>"></video>
            <% else %>
                <div class ='model-container'>
                    <babylon model = "<%= url_for(upload) %>" onLoad="window.location.reload()">
                </div>
            <% end %>
        <% end %>
    </div>
<% end %>


<%= @post.body %>

<div class="comments-container">
    <h3>Comments: (<%= @post.comments.size %>)</h3>
    <%= render partial: 'posts/comment', collection: @post.comments%>
    <% if current_user%>
        <%= render partial: 'comments/form'%>
    <% end %>
</div>

app/views/tags/edit.html.erb
<h2>Edit Tag</h2>
<%= form_with model: @tag do |f|%>
    <%= f.label 'Tag Name' %>
    <%= f.text_field :name %>
    <%= f.submit %>
<%end%>

<%= button_to "Delete", @tag, method: :delete,data: { confirm: "Are you sure?" }, class: 'delete-btn' %>

app/views/tags/index.html.erb
<h2>All Post Tags</h2>
<div class="post-list-container">
    <% @tags.each do |tag|%>
        <div class="post-item">
            <%= link_to tag.name, tag_path(tag), class: 'post-link'%>
        </div>
    <% end %>
</div>

app/views/tags/show.html.erb
<h2>Posts Tagged with '<%= @tag.name.capitalize%>' </h2>
<% if current_user != nil && current_user[:admin_user] %>
    <%= link_to 'Edit Tag', edit_tag_path(@tag)%>
<% end %>
<div class="post-list-container">
    <% @tag.posts.each do |post| %>
        <div class="post-item">
            <%= link_to post.title, post_path(post), class: 'post-link'%>
        </div>
    <%end%>
</div>

app/views/users/new.html.erb
<h2>Sign Up!</h2>
<%= form_with model: @user,  class: 'form' do |f| %>
    <p>
        <%= f.label :username %>
        <%= f.text_field :username, required: true%>
    </p>
    <p>
        <%= f.label :email %>
        <%= f.email_field :email, required: true%>
    </p>
    <p>
        <%= f.label :password %>
        <%= f.password_field :password, required: true%>
    </p>
    <p>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, required: true%>
    </p>
    
    <p class = 'submit-container'>
        <%= f.submit 'Sign Up!'%>
    </p>
<% end %>